apiVersion: v1
kind: Service
metadata:
  name: "{{ include "fullname" . }}-server"
  annotations:
    helm.sh/created: "{{ .Release.Time.Seconds }}"
  labels:
    app: "{{ include "fullname" . }}"
    component: "{{ include "fullname" . }}-server"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.internalPort }}
  - name: grpc
    port: {{ .Values.service.grpc.externalPort }}
    targetPort: {{ .Values.service.grpc.internalPort }}
  selector:
    component: {{ include "fullname" . }}-server
